/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package people;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
//import people.Login;
/**
 *
 * @author rbs
 */
public final class DisplayDep extends javax.swing.JDialog {

    /**
     * Creates new form Display_dep
     */
    public DisplayDep() {
        initComponents();
        showDepartments();
    }

    
    public static ArrayList<Department> getDepartmentList(){
    
        ArrayList<Department> deptList = new ArrayList<>();
        Connection connection = MyConnection.getConnection();
        
        String query = "SELECT * FROM dept";
        Statement st;
        ResultSet rs;
        
        try{
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Department dept;
            
            while(rs.next()){
               
                dept = new Department(rs.getString("deptid"), rs.getString("department"), rs.getString("description"));
                deptList.add(dept);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
        return deptList;
    }
    
    
// Displaying data in JTable
    
    public static void showDepartments(){
        ArrayList<Department> list = getDepartmentList();
        DefaultTableModel model = (DefaultTableModel)jTable_DEPTS.getModel();
        model.getDataVector().clear();
        Object[] row = new Object[3];
        for(int i= 0; i<list.size(); i++){
            row[0] = list.get(i).getDeptID();
            row[1] = list.get(i).Department();
            row[2] = list.get(i).Description();
            
            model.addRow(row);
        }
        
        model.fireTableDataChanged();
    }
    
    
    public void executeSQLQuery(String query, String message){
        Connection con = MyConnection.getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if(st.executeUpdate(query) == 1){
                Success suc = new Success();
                suc.setLocationRelativeTo(null);
                Success.jLabel_success2.setText("SUCCESS!!");
                Success.jLabel_success1.setText("Data has been "+ message);
                Success.jLabel_success.setText("Successfully");
                suc.setModalityType (ModalityType.APPLICATION_MODAL);
                suc.setVisible(true);
            }else{
                Error error = new Error();
                error.setLocationRelativeTo(null);
                Error.jLabel_error1.setText("ERROR!!");
                Error.jLabel_error.setText("No data has been "+ message);
                error.setModalityType (ModalityType.APPLICATION_MODAL);
                error.setVisible(true);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Deptid = new javax.swing.JLabel();
        Department = new javax.swing.JLabel();
        jTextField_deptid = new javax.swing.JTextField();
        jTextField_department = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DEPTS = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        jLabel_total = new javax.swing.JLabel();
        jLabel_welcome = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        jTextField_description = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1620, 870));

        Deptid.setText("Department ID");

        Department.setText("Department Name");

        jTextField_deptid.setEditable(false);
        jTextField_deptid.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jTextField_department.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jButton_add.setText("ADD DEPARTMENT");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jTable_DEPTS.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTable_DEPTS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DEPARTMENT ID", "DEPARTMENT", "DESCRIPTION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DEPTS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DEPTSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DEPTS);

        jButton1.setText("DELETE DEPARTMENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton_update.setText("EDIT ROW DATA");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/company.png"))); // NOI18N

        jLabel_total.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel_total.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_total.setText("TOTAL NUMBER OF DEPARTMENTS =");

        jLabel_welcome.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel_welcome.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_welcome.setText("Signed in as");

        Description.setText("Description");

        jTextField_description.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_deptid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Deptid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_department)
                                    .addComponent(Department, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(79, 79, 79))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_description, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deptid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_deptid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_department, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_description, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//The code below shows data on row selected by mouse click on the jTextFields respectivley
    private void jTable_DEPTSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DEPTSMouseClicked
        int i = jTable_DEPTS.getSelectedRow();
        TableModel model = jTable_DEPTS.getModel();
        jTextField_deptid.setText(model.getValueAt(i,0).toString());
        jTextField_department.setText(model.getValueAt(i,1).toString());
        jTextField_description.setText(model.getValueAt(i,2).toString());
    }//GEN-LAST:event_jTable_DEPTSMouseClicked

//Adding data in the Database
    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        AddDept ad = new AddDept();
        ad.setLocationRelativeTo(null);
        ad.setModalityType (ModalityType.APPLICATION_MODAL);
        ad.setVisible(true);
    }//GEN-LAST:event_jButton_addActionPerformed

//Editing data in the Database
    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        String query = "UPDATE dept SET   `department`= '"+jTextField_department.getText()+"', `description`= '"+jTextField_description.getText()+"' WHERE `deptid`= '"+jTextField_deptid.getText()+"'";
        executeSQLQuery(query, "updated");
        showDepartments();
//        this.dispose();
        DisplayDep.showDepartments();
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String query = "DELETE FROM dept WHERE deptid = '"+jTextField_deptid.getText()+"'";
        executeSQLQuery(query, "deleted");
        showDepartments();
        DisplayDep.showDepartments();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayDep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Department;
    private javax.swing.JLabel Deptid;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_update;
    public static javax.swing.JLabel jLabel_total;
    public static javax.swing.JLabel jLabel_welcome;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable_DEPTS;
    private javax.swing.JTextField jTextField_department;
    private javax.swing.JTextField jTextField_deptid;
    private javax.swing.JTextField jTextField_description;
    // End of variables declaration//GEN-END:variables
}
