
package people;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
//import people.Login;
/**
 *
 * @author rbs
 */
public final class DisplayTitle extends javax.swing.JDialog {

    /**
     * Creates new form Display_dep
     */
    public DisplayTitle() {
        initComponents();
        showTitles();
    }

    
    public static ArrayList<Title> getTitleList(){
    
        ArrayList<Title> titleList = new ArrayList<>();
        Connection connection = MyConnection.getConnection();
        
        String query = "SELECT * FROM title";
        Statement st;
        ResultSet rs;
        
        try{
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Title title;
            
            while(rs.next()){
               
                title = new Title(rs.getString("titleid"), rs.getString("title"), rs.getString("description"), rs.getString("salary"));
                titleList.add(title);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
        return titleList;
    }
    
    
// Displaying data in JTable
    
    public static void showTitles(){
        ArrayList<Title> list = getTitleList();
        DefaultTableModel model = (DefaultTableModel)jTable_TITLES.getModel();
        model.getDataVector().clear();
        Object[] row = new Object[4];
        for(int i= 0; i<list.size(); i++){
            row[0] = list.get(i).getTitleID();
            row[1] = list.get(i).Title();
            row[2] = list.get(i).Description();
            row[3] = list.get(i).Salary();
            
            model.addRow(row);
        }
        
        model.fireTableDataChanged();
    }
    
    
    public void executeSQLQuery(String query, String message){
        Connection con = MyConnection.getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if(st.executeUpdate(query) == 1){
                Success suc = new Success();
                suc.setLocationRelativeTo(null);
                Success.jLabel_success2.setText("SUCCESS!!");
                Success.jLabel_success1.setText("Data has been "+ message);
                Success.jLabel_success.setText("Successfully");
                suc.setModalityType (ModalityType.APPLICATION_MODAL);
                suc.setVisible(true);
            }else{
                Error error = new Error();
                error.setLocationRelativeTo(null);
                Error.jLabel_error1.setText("ERROR!!");
                Error.jLabel_error.setText("No data has been "+ message);
                error.setModalityType (ModalityType.APPLICATION_MODAL);
                error.setVisible(true);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titleid = new javax.swing.JLabel();
        Department = new javax.swing.JLabel();
        jTextField_titleid = new javax.swing.JTextField();
        jTextField_title = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_TITLES = new javax.swing.JTable();
        jButton_delete = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        jLabel_total = new javax.swing.JLabel();
        jLabel_welcome = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        jTextField_description = new javax.swing.JTextField();
        jTextField_salary = new javax.swing.JTextField();
        Salary = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Titleid.setText("Title ID");

        Department.setText("Title Name");

        jTextField_titleid.setEditable(false);
        jTextField_titleid.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jTextField_title.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jButton_add.setText("ADD TITLE");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jTable_TITLES.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTable_TITLES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TITLE ID", "TITLE", "DESCRIPTION", "SALARY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_TITLES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_TITLESMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_TITLES);

        jButton_delete.setText("DELETE TITLE");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_update.setText("EDIT ROW DATA");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/company.png"))); // NOI18N

        jLabel_total.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel_total.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_total.setText("TOTAL NUMBER OF TITLES =");

        jLabel_welcome.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel_welcome.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_welcome.setText("Signed in as");

        Description.setText("Description");

        jTextField_description.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jTextField_salary.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        Salary.setText("Salary");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_titleid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Titleid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(171, 171, 171)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_title)
                                            .addComponent(Department, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                                        .addGap(474, 474, 474)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_description)
                                    .addComponent(Description, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titleid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_titleid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_title, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_description, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//The code below shows data on row selected by mouse click on the jTextFields respectivley
    private void jTable_TITLESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_TITLESMouseClicked
        int i = jTable_TITLES.getSelectedRow();
        TableModel model = jTable_TITLES.getModel();
        jTextField_titleid.setText(model.getValueAt(i,0).toString());
        jTextField_title.setText(model.getValueAt(i,1).toString());
        jTextField_description.setText(model.getValueAt(i,2).toString());
        jTextField_salary.setText(model.getValueAt(i,3).toString());
    }//GEN-LAST:event_jTable_TITLESMouseClicked

//Adding data in the Database
    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        AddTitle ad = new AddTitle();
        ad.setLocationRelativeTo(null);
        ad.setModalityType (ModalityType.APPLICATION_MODAL);
        ad.setVisible(true);
    }//GEN-LAST:event_jButton_addActionPerformed

//Editing data in the Database
    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        String query = "UPDATE title SET title = '"+jTextField_title.getText()+"', `description`= '"+jTextField_description.getText()+"', salary = '"+jTextField_salary.getText()+"' WHERE `titleid`= '"+jTextField_titleid.getText()+"'";
        executeSQLQuery(query, "updated");
        showTitles();
//        this.dispose();
        DisplayTitle.showTitles();
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        String query = "DELETE FROM title WHERE titleid = '"+jTextField_titleid.getText()+"'";
        executeSQLQuery(query, "deleted");
        showTitles();
        DisplayTitle.showTitles();
        
    }//GEN-LAST:event_jButton_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayTitle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Department;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Salary;
    private javax.swing.JLabel Titleid;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_update;
    public static javax.swing.JLabel jLabel_total;
    public static javax.swing.JLabel jLabel_welcome;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable_TITLES;
    private javax.swing.JTextField jTextField_description;
    private javax.swing.JTextField jTextField_salary;
    private javax.swing.JTextField jTextField_title;
    private javax.swing.JTextField jTextField_titleid;
    // End of variables declaration//GEN-END:variables
}
