/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package refined;

import people.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
//import people.Login;
/**
 *
 * @author rbs
 */
public final class DisplayEmp extends javax.swing.JDialog {

    /**
     * Creates new form Display_emp
     */
    public DisplayEmp() {
        initComponents();
        showEmployees();
    }
    

    
    public static ArrayList<Employee> getEmployeeList(){
    
        ArrayList<Employee> empList = new ArrayList<>();
        Connection connection = MyConnection.getConnection();
        
        String query = "SELECT emp.id, concat(ecode, emp.id) as empid, firstname, lastname, gender, department, title, phone, email, empdate FROM emp, dept, title WHERE emp.dept_id=dept.id && emp.title_id=title.id";
        Statement st;
        ResultSet rs;
        
        try{
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Employee emp;
            
            while(rs.next()){
               
                emp = new Employee(rs.getInt("id"),rs.getString("empid"), rs.getString("firstname"), rs.getString("lastname"), rs.getString("gender"), rs.getString("department"), rs.getString("title"), rs.getString("phone"), rs.getString("email"), rs.getString("empdate"));
                empList.add(emp);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
        return empList;
    }
    
    
// Displaying data in JTable
    
    public static void showEmployees(){
        ArrayList<Employee> list = getEmployeeList();
        DefaultTableModel model = (DefaultTableModel)jTable_EMPLOYEE.getModel();
        model.getDataVector().clear();
        Object[] row = new Object[10];
        for(int i= 0; i<list.size(); i++){
            row[0] = list.get(i).getId();
            row[1] = list.get(i).EmpID();
            row[2] = list.get(i).FirstName();
            row[3] = list.get(i).LastName();
            row[4] = list.get(i).Gender();
            row[5] = list.get(i).Department();
            row[6] = list.get(i).Title();
            row[7] = list.get(i).Phone();
            row[8] = list.get(i).Email();
            row[9] = list.get(i).EmpDate();
            
            model.addRow(row);
        }
        
        model.fireTableDataChanged();
    }
    
    
    public void executeSQLQuery(String query, String message){
        Connection con = MyConnection.getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if(st.executeUpdate(query) == 1){
                Success suc = new Success();
                suc.setLocationRelativeTo(null);
                Success.jLabel_success2.setText("SUCCESS!!");
                Success.jLabel_success1.setText("Data has been "+ message);
                Success.jLabel_success.setText("Successfully");
                suc.setModalityType (ModalityType.APPLICATION_MODAL);
                suc.setVisible(true);
            }else{
                Error error = new Error();
                error.setLocationRelativeTo(null);
                Error.jLabel_error1.setText("ERROR!!");
                Error.jLabel_error.setText("No data has been "+ message);
                error.setModalityType (ModalityType.APPLICATION_MODAL);
                error.setVisible(true);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_EMPLOYEE = new javax.swing.JTable();
        jButton_manage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_total = new javax.swing.JLabel();
        jLabel_welcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 880));

        jTable_EMPLOYEE.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTable_EMPLOYEE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "EMPLOYEE ID", "FIRST NAME", "LAST NAME", "GENDER", "DEPARTMENT", "JOB TITLE", "PHONE", "EMAIL", "DATE EMPLOYED"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_EMPLOYEE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_EMPLOYEEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_EMPLOYEE);

        jButton_manage.setText("MANAGE EMPLOYEES");
        jButton_manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_manageActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/company.png"))); // NOI18N

        jLabel_total.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel_total.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_total.setText("TOTAL NUMBER OF EMPLOYEES =");

        jLabel_welcome.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel_welcome.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_welcome.setText("Signed in as");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(372, 372, 372)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_total, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                        .addContainerGap(251, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(311, 311, 311))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jButton_manage, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_manage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//The code below shows data on row selected by mouse click on the jTextFields respectivley
    private void jTable_EMPLOYEEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_EMPLOYEEMouseClicked
        
        
    }//GEN-LAST:event_jTable_EMPLOYEEMouseClicked

//Editing data in the Database
    private void jButton_manageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_manageActionPerformed
        ManageEmp man = new ManageEmp();
        man.setLocationRelativeTo(null);
        ManageEmp.jLabel_welcome.setText("Signed in as "+ Login.jTextField_User.getText());
        ManageEmp.jLabel_total.setText("TOTAL NUMBER OF EMPLOYEES IS ("+Integer.toString(MyFunction.countData("emp"))+")");
        man.setModalityType (ModalityType.APPLICATION_MODAL);
        man.setVisible(true);
    }//GEN-LAST:event_jButton_manageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_manage;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel_total;
    public static javax.swing.JLabel jLabel_welcome;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable_EMPLOYEE;
    // End of variables declaration//GEN-END:variables
}
