/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package refined;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
//import people.Login;
/**
 *
 * @author rbs
 */
public final class DisplayEmpSalary extends javax.swing.JDialog {

    /**
     * Creates new form Display_emp
     */
    public DisplayEmpSalary() {
        initComponents();
        showEmpSalary();
    }

    
    public static ArrayList<EmpSalary> getEmpSalaryList(){
    
        ArrayList<EmpSalary> salList = new ArrayList<>();
        Connection connection = MyConnection.getConnection();
        
        String query = "SELECT emp.id, CONCAT(ecode, emp.id) AS empid, firstname, lastname, department, title, salary FROM emp, dept, title WHERE emp.dept_id=dept.id && emp.title_id=title.id";
        Statement st;
        ResultSet rs;
        
        try{
            st = connection.createStatement();
            rs = st.executeQuery(query);
            EmpSalary sal;
            
            while(rs.next()){
               
                sal = new EmpSalary(rs.getInt("id"), rs.getString("empid"), rs.getString("firstname"), rs.getString("lastname"), rs.getString("department"), rs.getString("title"), rs.getString("salary"));
                salList.add(sal);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
        return salList;
    }
    
    
// Displaying data in JTable
    
    public static void showEmpSalary(){
        ArrayList<EmpSalary> list = getEmpSalaryList();
        DefaultTableModel model = (DefaultTableModel)jTable_EMPSALARY.getModel();
        model.getDataVector().clear();
        Object[] row = new Object[7];
        for(int i= 0; i<list.size(); i++){
            row[0] = list.get(i).getID();
            row[1] = list.get(i).EmpID();
            row[2] = list.get(i).FirstName();
            row[3] = list.get(i).LastName();
            row[4] = list.get(i).Department();
            row[5] = list.get(i).Title();
            row[6] = list.get(i).Salary();
            
            model.addRow(row);
        }
        
        model.fireTableDataChanged();
    }
    
    
    public void executeSQLQuery(String query, String message){
        Connection con = MyConnection.getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if(st.executeUpdate(query) == 1){
                Success suc = new Success();
                suc.setLocationRelativeTo(null);
                Success.jLabel_success2.setText("SUCCESS!!");
                Success.jLabel_success1.setText("Data has been "+ message);
                Success.jLabel_success.setText("Successfully");
                suc.setModalityType (ModalityType.APPLICATION_MODAL);
                suc.setVisible(true);
            }else{
                Error error = new Error();
                error.setLocationRelativeTo(null);
                Error.jLabel_error1.setText("ERROR!!");
                Error.jLabel_error.setText("No data has been "+ message);
                error.setModalityType (ModalityType.APPLICATION_MODAL);
                error.setVisible(true);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_EMPSALARY = new javax.swing.JTable();
        jButton_manage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_total = new javax.swing.JLabel();
        jLabel_welcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 880));

        jTable_EMPSALARY.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTable_EMPSALARY.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "EMPLOYEE ID", "FIRST NAME", "LAST NAME", "DEPARTMENT", "TITLE", "SALARY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_EMPSALARY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_EMPSALARYMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_EMPSALARY);

        jButton_manage.setText("MANAGE EMPLOYEES");
        jButton_manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_manageActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/company.png"))); // NOI18N

        jLabel_total.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel_total.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_total.setText("TOTAL NUMBER OF EMPLOYEES =");

        jLabel_welcome.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel_welcome.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_welcome.setText("Signed in as");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(377, 377, 377)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jButton_manage, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_manage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//The code below shows data on row selected by mouse click on the jTextFields respectivley
    private void jTable_EMPSALARYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_EMPSALARYMouseClicked
        
        
    }//GEN-LAST:event_jTable_EMPSALARYMouseClicked

//Editing data in the Database
    private void jButton_manageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_manageActionPerformed
        ManageEmpSal man = new ManageEmpSal();
        man.setLocationRelativeTo(null);
        ManageEmpSal.jLabel_welcome.setText("Signed in as "+ Login.jTextField_User.getText());
        ManageEmpSal.jLabel_total.setText("TOTAL NUMBER OF EMPLOYEES IS ("+Integer.toString(MyFunction.countData("emp"))+")");
        man.setModalityType (ModalityType.APPLICATION_MODAL);
        man.setVisible(true);
    }//GEN-LAST:event_jButton_manageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayEmpSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_manage;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel_total;
    public static javax.swing.JLabel jLabel_welcome;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable_EMPSALARY;
    // End of variables declaration//GEN-END:variables
}
